### ISSUE TITLE
C192 shows 10n on schematics, could it possibly be 10p?

### ISSUE THREAD

**Issue by jeffs555** [mentalDetector/Quansheng_UV-K5_PCB_R51-V1.4_PCB_Reversing_Rev._0.9#4]
Was doing spice simulation of the FM and VHF input filtering and the 10n value you show for C192 basically kills the VHF and FM response. Simulation shows a 10n C192 peaks the input signal at about 1MHz and drops the input on two meters by 60db. 
Simulation with a 10p C192 shows a reasonable passband for VHF and high HF.

PS Thanks for all the hard work on reverse engineering the schematics.

**Comment by mentalDetector** [comment]
Thanks for the nice words. It was a pleasure for me to give something back to the community.

C192 indeed was an error in the schematics which has been pointed out some months ago. I included this in the errata at the bottom of the main page of this project. Initially it showed a correct value of 20pF for the capacitor. After your comment now I checked Ludwich's and my table. This shows that I had measured the value myself with a VNA and found 22pF. I have change the value in the errata now to 22pF.

Please use 22pF for your simulation :-) 

If you find further errors, please raise new issues here. If you at one point want to share your simulation file, please let Ludwich or me know.

**Comment by jeffs555** [comment]
Thanks for the quick response. I only looked at your PDF schematics, should have looked at the readme too.
Was looking at doing the SI4732 mod and some versions of the mod replace L4 and C23 with higher values. Was just simulating to see what effect they have on the HF response. Would certainly share sim files when I get done.
